ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.AutomaticFrameAdvance = true
ENT.Model =  "models/zerochain/props_weedfarm/zwf_drystation.mdl"
ENT.Spawnable = true
ENT.AdminSpawnable = false
ENT.PrintName = "Dry Station"
ENT.Category = "Zeros GrowOP"
ENT.RenderGroup = RENDERGROUP_OPAQUE
