local t = {
    {'Weed', "trails/weed"},
    {'Colors', "trails/colors"},
    {'Skull', "trails/skull"},
    {'Ghost', "trails/ghost"},
    {'Sweets', "trails/sweets"},
    {'Hand', "trails/hand"},
    {'Cloud', "trails/cloud"},
    {'Burger', "trails/burger"},
    {'Bucket', "trails/bucket"},
    {'Ball', "trails/ball"},
    {'Fire', "trails/fire"},
    {'Toxic', "trails/toxic"},
    {'Batman', "trails/flagabatmana"},
    {"Dat Boi", 'trails/boi'},
    {"Gabe", 'trails/gabe'},
    {'Xmas Tree', 'trails/tree.vmt'},
    {'Sword', 'trails/sword.vmt'},
    {'Railways', 'trails/railways.vmt'},
    {'Paws', 'trails/paws.vmt'},
    {'Music Note', 'trails/note.vmt'},
    {'Light', 'trails/light.vmt'},
    {'Kappa', 'trails/kappa.vmt'},
    {'Uganda Knuckles', 'trails/ugandaknuckles.vmt'},
    {'Vader', 'trails/vader'},
    {'White Music', 'trails/whitemusic'},
    {'Xbox', 'trails/xboxv2'},
    {'Yellow Pacman', 'trails/yellowpacman'},
    {'Zodiac', 'trails/zodiac'},
    {'Zoidberg', 'trails/zoidberg'},
    {'Ace', 'trails/ace'},
    {'Alche', 'trails/alche'},
    {'America', 'trails/america'},
    {'Android', 'trails/android'},
    {'Angry', 'trails/angry'},
    {'Anime', 'trails/anime'},
    {'Apple', 'trails/apple'},
    {'Arrow', 'trails/arrow'},
    {'b1', 'trails/b1'},
    {'Bender', 'trails/bender'},
    {'Blood', 'trails/blood'},
    {'Blue Pacman', 'trails/bluepacman'},
    {'Bubbles', 'trails/bubbles'},
    {'Bunchocreeps', 'trails/bunchocreeps'},
    {'Canada', 'trails/canada'},
    {'Carebear', 'trails/carebear'},
    {'Chrome', 'trails/chromev2'},
    {'Coolsun', 'trails/coolsun'},
    {'Creeper', 'trails/creeper'},
    {'Cursor', 'trails/cursor'},
    {'Dennis', 'trails/dennis'},
    {'Doge', 'trails/doge'},
    {'Dog paws', 'trails/dogpaws'},
    {'Dollar', 'trails/dollar'},
    {'England', 'trails/england'},
    {'Epiclulz', 'trails/epiclulz'},
    {'Fairy Tail', 'trails/fairy-tail'},
    {'Fish', 'trails/fishinthesea'},
    {'Footprints', 'trails/footprints'},
    {'France', 'trails/france'},
    {'Fry', 'trails/fry'},
    {'Ger', 'trails/ger'},
    {'Germany', 'trails/germany'},
    {'Girl power', 'trails/girlpower'},
    {'Goku', 'trails/goku'},
    {'Ha', 'trails/ha'},
    {'Handy', 'trails/handy'},
    {'Happy', 'trails/happy'},
    {'Heart', 'trails/heartk'},
    {'Ironman', 'trails/ironman'},
    {'Jim Jam', 'trails/jimjam'},
    {'Hitty cat chat', 'trails/kittycatchat'},
    {'Litfuse', 'trails/litfuse'},
    {'Luffy', 'trails/luffy'},
    {'Maletrail', 'trails/maletrail'},
    {'Minecraft', 'trails/minecraft'},
    {'Money', 'trails/money'},
    {'Muffin', 'trails/muffin'},
    {'Muffin Kawaii', 'trails/muffinkawaii'},
    {'Notes', 'trails/musicalnotes'},
    {'Naruto', 'trails/naruto'},
    {'Nibbler', 'trails/nibbler'},
    {'Pacman', 'trails/pacman'},
    {'Pink Pacman', 'trails/pinkpacman'},
    {'Pirateship', 'trails/pirateship'},
    {'Playstation', 'trails/playstation'},
    {'Pokeball', 'trails/pokeballv2'},
    {'Portal', 'trails/portal'},
    {'Gift', 'trails/present'},
    {'PSV2', 'trails/psv2'},
    {'Question', 'trails/question'},
    {'Rabbit', 'trails/rabbit'},
    {'Rainbow', 'trails/rainbow'},
    {'Rainbow Wave 2', 'trails/rainbowwave2'},
    {'Red Arrow', 'trails/redarrow'},
    {'Red Pacman', 'trails/redpacman'},
    {'Red Stars', 'trails/redstars'},
    {'Rubber Ducks', 'trails/rubberducks'},
    {'Rubiks Cube', 'trails/rubiks'},
    {'Sasuke', 'trails/sasuke'},
    {'Shoes', 'trails/shoes'},
    {'Smiley', 'trails/smiley'},
    {'Smouch', 'trails/smouch'},
    {'Snowflake', 'trails/snowflake'},
    {'Spooky Black', 'trails/spookyblack'},
    {'Spooky', 'trails/spookyerd'},
    {'Star', 'trails/star'},
    {'Stars And Moon', 'trails/starsnmoons'},
    {'Suit', 'trails/suit'},
    {'Sun and Clouds', 'trails/sunsnclouds'},
    {'Trains', 'trails/trains'},
    {'Twisted Rainbow', 'trails/twistedrainbow'}
}

local items = {}

for k, v in pairs(t) do
    table.insert(items, {
        name = v[1],
        rendering = 1,
        metadata = {
            true,
            v[2],
            false
        }
    })
end

ashop.RegisterPremade("AShop Trails", {
    requireWorkshop = "",

    objectTypes = {
        {
            "Trails",
        }
    },

    items = items
})