hook.Add("DarkRPFinishedLoading", "AShop_currencies_darkrp", function()
    ashop.currencies.RegisterCurrency("DarkRP", function(ply, amt)
        ply:addMoney(amt)
    end, function(ply)
        return ply:getDarkRPVar("money")
    end, function(amt)
        return DarkRP.formatMoney(amt)
    end)
end)
