-- Français
BaseWars:AddTranslation("pointshop_tabPlayer", "fr", "Vos Skins")
BaseWars:AddTranslation("pointshop_tabShop", "fr", "Shop Pointshop")
BaseWars:AddTranslation("pointshop_tabCreditShop", "fr", "Shop Credits")
BaseWars:AddTranslation("pointshop_title_model", "fr", "Model du skin")
BaseWars:AddTranslation("pointshop_textEntry_model", "fr", "Entrez un model")
BaseWars:AddTranslation("pointshop_title_price", "fr", "Prix du skin")
BaseWars:AddTranslation("pointshop_textEntry_price", "fr", "Entrez un prix")
BaseWars:AddTranslation("pointshop_title_vip", "fr", "Skin VIP")
BaseWars:AddTranslation("pointshop_everyone", "fr", "Tout Le Monde")
BaseWars:AddTranslation("pointshop_vip", "fr", "VIP")
BaseWars:AddTranslation("pointshop_addSkin", "fr", "Ajouter le skin")
BaseWars:AddTranslation("pointshop_invalidModel", "fr", "Le model n'est pas valide")
BaseWars:AddTranslation("pointshop_invalidPrice", "fr", "Le prix n'est pas valide")
BaseWars:AddTranslation("pointshop_pricePointshop", "fr", "%s PS")
BaseWars:AddTranslation("pointshop_priceCredit", "fr", "%s Credits")
BaseWars:AddTranslation("pointshop_tooExpensive", "fr", "Ce skin est trop cher")
BaseWars:AddTranslation("pointshop_playerPointshop", "fr", "%s Pointshop")
BaseWars:AddTranslation("pointshop_owned", "fr", "POSSÉDÉE")
BaseWars:AddTranslation("pointshop_addedSkin", "fr", "Vous avez ajouté un skin au prix de %s PS avec le model \"%s\" [VIP: %s]")
BaseWars:AddTranslation("pointshop_skinIDInvalid", "fr", "Ce skin n'est pas valide")
BaseWars:AddTranslation("pointshop_removedSkin", "fr", "Vous avez retiré un skin")
BaseWars:AddTranslation("pointshop_boughtSkin", "fr", "Vous avez acheté un skin pour %s PS")
BaseWars:AddTranslation("pointshop_vipSkin", "fr", "Ce skin est seulement pour les VIP")
BaseWars:AddTranslation("pointshop_vipOnly", "fr", "VIP Seulement")
BaseWars:AddTranslation("pointshop_buyFor", "fr", "Acheter pour %s PS")
BaseWars:AddTranslation("pointshop_slowdown", "fr", "Ralentissez")
BaseWars:AddTranslation("pointshop_changedActiveSkin", "fr", "Vous avez changé votre skin")
BaseWars:AddTranslation("pointshop_playerCredit", "fr", "%s Credits")
BaseWars:AddTranslation("pointshop_buyCreditItem", "fr", "Vous avez acheté \"%s\" pour %s")
BaseWars:AddTranslation("pointshop_playPointshop", "fr", "Vous avez reçu %s pointshop pour avoir joué")
BaseWars:AddTranslation("pointshop_playCredit", "fr", "Vous avez reçu 10 credits pour avoir joué")
BaseWars:AddTranslation("pointshop_gaveSkinTo", "fr", "Vous avez donné un skin à %s | SkinID »  %s")
BaseWars:AddTranslation("pointshop_playerHasSkin", "fr", "Ce joueur a déjâ ce skin | SkinID » %s")
BaseWars:AddTranslation("pointshop_idCopied", "fr", "ID du skin copié")

-- English
BaseWars:AddTranslation("pointshop_tabPlayer", "en", "Your Skins")
BaseWars:AddTranslation("pointshop_tabShop", "en", "Pointshop Shop")
BaseWars:AddTranslation("pointshop_tabCreditShop", "en", "Credits Shop")
BaseWars:AddTranslation("pointshop_title_model", "en", "Model of the skin")
BaseWars:AddTranslation("pointshop_textEntry_model", "en", "Enter a model")
BaseWars:AddTranslation("pointshop_title_price", "en", "Price of the skin")
BaseWars:AddTranslation("pointshop_textEntry_price", "en", "Enter a price")
BaseWars:AddTranslation("pointshop_title_vip", "en", "VIP Skin")
BaseWars:AddTranslation("pointshop_everyone", "en", "Everyone")
BaseWars:AddTranslation("pointshop_vip", "en", "VIP")
BaseWars:AddTranslation("pointshop_addSkin", "en", "Add the skin")
BaseWars:AddTranslation("pointshop_invalidModel", "en", "The model is not valid")
BaseWars:AddTranslation("pointshop_invalidPrice", "en", "The price is not valid")
BaseWars:AddTranslation("pointshop_pricePointshop", "en", "%s PS")
BaseWars:AddTranslation("pointshop_priceCredit", "en", "%s Credits")
BaseWars:AddTranslation("pointshop_tooExpensive", "en", "This skin is too expensive")
BaseWars:AddTranslation("pointshop_playerPointshop", "en", "%s Pointshop")
BaseWars:AddTranslation("pointshop_owned", "en", "OWNED")
BaseWars:AddTranslation("pointshop_addedSkin", "en", "You added a skin at the price of %s PS with the model \"%s\" [VIP: %s]")
BaseWars:AddTranslation("pointshop_skinIDInvalid", "en", "This skin is not valid")
BaseWars:AddTranslation("pointshop_removedSkin", "en", "You have removed a skin")
BaseWars:AddTranslation("pointshop_boughtSkin", "en", "You bought a skin for %s PS")
BaseWars:AddTranslation("pointshop_vipSkin", "en", "This skin is for VIP only")
BaseWars:AddTranslation("pointshop_vipOnly", "en", "VIP Only")
BaseWars:AddTranslation("pointshop_buyFor", "en", "Buy for %s PS")
BaseWars:AddTranslation("pointshop_slowdown", "en", "Slowdown")
BaseWars:AddTranslation("pointshop_changedActiveSkin", "en", "You changed your active skin")
BaseWars:AddTranslation("pointshop_playerCredit", "en", "%s Credits")
BaseWars:AddTranslation("pointshop_buyCreditItem", "en", "You bought \"%s\" for %s")
BaseWars:AddTranslation("pointshop_playPointshop", "en", "You received %s pointshop for playing")
BaseWars:AddTranslation("pointshop_playCredit", "en", "You received 10 credits for playing")
BaseWars:AddTranslation("pointshop_gaveSkinTo", "en", "You gave a skin to %s | SkinID » %s")
BaseWars:AddTranslation("pointshop_playerHasSkin", "en", "This player already has this skin | SkinID » %s")
BaseWars:AddTranslation("pointshop_idCopied", "en", "Skin ID Copied")

if CLIENT then
    hook.Add("BaseWars:Initialize", "BaseWars:Module/Pointshop", function()
        BaseWars:AddBaseWarsMenuTab("Pointshop", "basewars_materials/f3/pointshop.png", "BaseWars.F3Menu.Pointshop", 6)
    end)
end